#!/bin/bash
echo Combining books into ase-kjv_usfx.xml
echo "<?xml version=\"1.0\" encoding=\"utf-8\"?><usfx xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:noNamespaceSchemaLocation=\"usfx.xsd\"><languageCode>ase</languageCode>" > ase-kjv_usfx.xml
cat FRT.usfx >> ase-kjv_usfx.xml
cat GEN.usfx >> ase-kjv_usfx.xml
cat EXO.usfx >> ase-kjv_usfx.xml
cat LEV.usfx >> ase-kjv_usfx.xml
cat NUM.usfx >> ase-kjv_usfx.xml
cat DEU.usfx >> ase-kjv_usfx.xml
cat JOS.usfx >> ase-kjv_usfx.xml
cat JDG.usfx >> ase-kjv_usfx.xml
cat RUT.usfx >> ase-kjv_usfx.xml
cat 1SA.usfx >> ase-kjv_usfx.xml
cat 2SA.usfx >> ase-kjv_usfx.xml
cat 1KI.usfx >> ase-kjv_usfx.xml
cat 2KI.usfx >> ase-kjv_usfx.xml
cat 1CH.usfx >> ase-kjv_usfx.xml
cat 2CH.usfx >> ase-kjv_usfx.xml
cat EZR.usfx >> ase-kjv_usfx.xml
cat NEH.usfx >> ase-kjv_usfx.xml
cat EST.usfx >> ase-kjv_usfx.xml
cat JOB.usfx >> ase-kjv_usfx.xml
cat PSA.usfx >> ase-kjv_usfx.xml
cat PRO.usfx >> ase-kjv_usfx.xml
cat ECC.usfx >> ase-kjv_usfx.xml
cat SNG.usfx >> ase-kjv_usfx.xml
cat ISA.usfx >> ase-kjv_usfx.xml
cat JER.usfx >> ase-kjv_usfx.xml
cat LAM.usfx >> ase-kjv_usfx.xml
cat EZK.usfx >> ase-kjv_usfx.xml
cat DAN.usfx >> ase-kjv_usfx.xml
cat HOS.usfx >> ase-kjv_usfx.xml
cat JOL.usfx >> ase-kjv_usfx.xml
cat AMO.usfx >> ase-kjv_usfx.xml
cat OBA.usfx >> ase-kjv_usfx.xml
cat JON.usfx >> ase-kjv_usfx.xml
cat MIC.usfx >> ase-kjv_usfx.xml
cat NAM.usfx >> ase-kjv_usfx.xml
cat HAB.usfx >> ase-kjv_usfx.xml
cat ZEP.usfx >> ase-kjv_usfx.xml
cat HAG.usfx >> ase-kjv_usfx.xml
cat ZEC.usfx >> ase-kjv_usfx.xml
cat MAL.usfx >> ase-kjv_usfx.xml
cat TOB.usfx >> ase-kjv_usfx.xml
cat JDT.usfx >> ase-kjv_usfx.xml
cat ESG.usfx >> ase-kjv_usfx.xml
cat WIS.usfx >> ase-kjv_usfx.xml
cat SIR.usfx >> ase-kjv_usfx.xml
cat BAR.usfx >> ase-kjv_usfx.xml
cat S3Y.usfx >> ase-kjv_usfx.xml
cat SUS.usfx >> ase-kjv_usfx.xml
cat BEL.usfx >> ase-kjv_usfx.xml
cat 1MA.usfx >> ase-kjv_usfx.xml
cat 2MA.usfx >> ase-kjv_usfx.xml
cat 1ES.usfx >> ase-kjv_usfx.xml
cat MAN.usfx >> ase-kjv_usfx.xml
cat 2ES.usfx >> ase-kjv_usfx.xml
cat MAT.usfx >> ase-kjv_usfx.xml
cat MRK.usfx >> ase-kjv_usfx.xml
cat LUK.usfx >> ase-kjv_usfx.xml
cat JHN.usfx >> ase-kjv_usfx.xml
cat ACT.usfx >> ase-kjv_usfx.xml
cat ROM.usfx >> ase-kjv_usfx.xml
cat 1CO.usfx >> ase-kjv_usfx.xml
cat 2CO.usfx >> ase-kjv_usfx.xml
cat GAL.usfx >> ase-kjv_usfx.xml
cat EPH.usfx >> ase-kjv_usfx.xml
cat PHP.usfx >> ase-kjv_usfx.xml
cat COL.usfx >> ase-kjv_usfx.xml
cat 1TH.usfx >> ase-kjv_usfx.xml
cat 2TH.usfx >> ase-kjv_usfx.xml
cat 1TI.usfx >> ase-kjv_usfx.xml
cat 2TI.usfx >> ase-kjv_usfx.xml
cat TIT.usfx >> ase-kjv_usfx.xml
cat PHM.usfx >> ase-kjv_usfx.xml
cat HEB.usfx >> ase-kjv_usfx.xml
cat JAS.usfx >> ase-kjv_usfx.xml
cat 1PE.usfx >> ase-kjv_usfx.xml
cat 2PE.usfx >> ase-kjv_usfx.xml
cat 1JN.usfx >> ase-kjv_usfx.xml
cat 2JN.usfx >> ase-kjv_usfx.xml
cat 3JN.usfx >> ase-kjv_usfx.xml
cat JUD.usfx >> ase-kjv_usfx.xml
cat REV.usfx >> ase-kjv_usfx.xml
echo "</usfx>" >> ase-kjv_usfx.xml

